#!/usr/bin/env python

from sys import stdout, stderr
from src import *


class DbBot(object):
    def __init__(self):
        self._config = Configuration()
        database = ':memory:' if self._config.dry_run else self._config.db_file_path
        self._db = SQLDatabase(database, self._output_verbose)
        self._parser = ResultsParser(
            self._config.include_keywords,
            self._db,
            self._output_verbose
        )

    def run(self):
        try:
            for xml_file in self._config.file_paths:
                self._parser.xml_to_db(xml_file)
                self._db.commit()
        except Exception, message:
            stderr.write('dbbot: error: %s\n\n' % message)
            exit(1)
        finally:
            self._db.close()

    def _output_verbose(self, message, header):
        if self._config.be_verbose:
            stdout.write(' %-8s |   %s\n' % (header, message))


if __name__ == '__main__':
    DbBot().run()
